### ISSUE TITLE
Fish Shell don't use alias command in config

### ISSUE THREAD

**Issue by Aiz0** [dCaples/quickalias#5]
From the Fish shell documentation about [defining aliases](https://fishshell.com/docs/current/language.html#defining-aliases)
_Unlike other shells, this just makes functions - fish has no separate concept of an “alias”, we just use the word for a function wrapper like this. `alias` immediately creates a function. Consider using `alias --save` or `funcsave` to save the created function into an autoload file instead of recreating the alias each time._

Adding alias into the configuration file creates a function each time the configuration is read.
This is not recommended.
There are three solutions to this.

1. use [abbreviations](https://fishshell.com/docs/current/cmds/abbr.html) instead. They should be created as global if put into config

2. create the function using `alias --save` with python

3. create a file with the function in the users autoload function directory

If you use fish, I would recommend using  `alias --save NAME DEFINITION` instead. You could create a abbreviation or function for it if you don't want to type `--save` every time.

**Comment by ladysharkyshark** [comment]
I think my fix for this works.
